services:
    app:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: appUpsend
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        ports:
            - "5173:5173" # Porta do Vite
            - "9003:9003" # Porta do Xdebug
        networks:
            - upsend_network

    webserver:
        image: nginx:alpine
        container_name: webserverUpsend
        restart: unless-stopped
        ports:
            - "9696:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - upsend_network

    db:
        image: mysql:5.7
        container_name: dbUpsend
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: laravel
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - upsend_network

networks:
    upsend_network:

volumes:
    dbdata:
